/*drop table "C##ST47130"."ZPUSOB_ZAKONCENI" cascade constraints;
drop table "C##ST47130"."ZPUSOB_VYUKY" cascade constraints;
drop table "C##ST47130"."VYUCUJICI" cascade constraints;
drop table "C##ST47130"."SEMESTR" cascade constraints;
drop table "C##ST47130"."ROZVRHOVA_AKCE" cascade constraints;
drop table "C##ST47130"."ROLE_VYUCUJICIHO" cascade constraints;
drop table "C##ST47130"."PREDMET" cascade constraints;
drop table "C##ST47130"."OBOR" cascade constraints;
drop table "C##ST47130"."OBOR_PREDMET" cascade constraints;
drop table "C##ST47130"."KATEGORIE_PREDMETU" cascade constraints;
drop table "C##ST47130"."KATEDRA" cascade constraints;
drop table "C##ST47130"."FORMA_VYUKY" cascade constraints;
drop table "C##ST47130"."FAKULTA" cascade constraints;*/

/*CREATE TABLE fakulta (
    zkratka_fakulty   VARCHAR2(10) NOT NULL,
    nazev_fakulty     VARCHAR2(60) NOT NULL
);

ALTER TABLE fakulta ADD CONSTRAINT fakulta_pk PRIMARY KEY ( zkratka_fakulty );

CREATE TABLE forma_vyuky (
    id_fv   NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    forma   VARCHAR2(30) NOT NULL
);

ALTER TABLE forma_vyuky ADD CONSTRAINT forma_vyuky_pk PRIMARY KEY ( id_fv );

CREATE TABLE katedra (
    zkratka_katedry           VARCHAR2(10) NOT NULL,
    nazev_katedry             VARCHAR2(60) NOT NULL,
    fakulta_zkratka_fakulty   VARCHAR2(10) NOT NULL
);

ALTER TABLE katedra ADD CONSTRAINT katedra_pk PRIMARY KEY ( zkratka_katedry );

CREATE TABLE kategorie_predmetu (
    kategorie   VARCHAR2(1) NOT NULL
);

ALTER TABLE kategorie_predmetu ADD CONSTRAINT kategorie_predmetu_pk PRIMARY KEY ( kategorie );

CREATE TABLE obor (
    zkratka_oboru             VARCHAR2(8) NOT NULL,
    nazev_oboru               VARCHAR2(50) NOT NULL,
    fakulta_zkratka_fakulty   VARCHAR2(10) NOT NULL
);

ALTER TABLE obor ADD CONSTRAINT obor_pk PRIMARY KEY ( zkratka_oboru );

CREATE TABLE obor_predmet (
    obor_zkratka_oboru             VARCHAR2(8) NOT NULL,
    predmet_zkratka_predmetu       VARCHAR2(8) NOT NULL,
    kategorie_predmetu_kategorie   VARCHAR2(1) NOT NULL
);

ALTER TABLE obor_predmet ADD CONSTRAINT obor_predmet_pk PRIMARY KEY ( obor_zkratka_oboru,
predmet_zkratka_predmetu );

CREATE TABLE predmet (
    zkratka_predmetu         VARCHAR2(8) NOT NULL,
    nazev_predmetu           VARCHAR2(255) NOT NULL,
    rozsah_hodin             NUMBER NOT NULL,
    doporuceny_rocnik        NUMBER,
    semestr_id_semestr       NUMBER NOT NULL,
    zpusob_zakonceni_id_zz   NUMBER NOT NULL,
    forma_vyuky_id_fv        NUMBER NOT NULL
);

ALTER TABLE predmet ADD CONSTRAINT predmet_pk PRIMARY KEY ( zkratka_predmetu );

CREATE TABLE role_vyucujiciho (
    role   VARCHAR2(40) NOT NULL
);

ALTER TABLE role_vyucujiciho ADD CONSTRAINT role_vyucujiciho_pk PRIMARY KEY ( role );

CREATE TABLE rozvrhova_akce (
    id_ra                      NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    pocet_studentu             NUMBER NOT NULL,
    mahodin                    NUMBER NOT NULL,
    zacinav                    NUMBER NOT NULL,
    predmet_zkratka_predmetu   VARCHAR2(8) NOT NULL,
    zpusob_vyuky_id_zv         NUMBER NOT NULL,
    role_vyucujiciho_role      VARCHAR2(40) NOT NULL,
    vyucujici_id_vyucujiciho   VARCHAR2(7) NOT NULL
);

ALTER TABLE rozvrhova_akce ADD CONSTRAINT rozvrhova_akce_pk PRIMARY KEY ( id_ra );

CREATE TABLE semestr (
    id_semestr   NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    sem          VARCHAR2(30) NOT NULL
);

ALTER TABLE semestr ADD CONSTRAINT semestr_pk PRIMARY KEY ( id_semestr );

CREATE TABLE vyucujici (
    id_vyucujiciho            VARCHAR2(7) NOT NULL,
    jmeno                     VARCHAR2(25) NOT NULL,
    prijmeni                  VARCHAR2(30) NOT NULL,
    titul_pred                VARCHAR2(20),
    titul_za                  VARCHAR2(15),
    telefon                   VARCHAR2(13),
    mobil                     VARCHAR2(13),
    email                     VARCHAR2(255) NOT NULL,
    katedra_zkratka_katedry   VARCHAR2(10) NOT NULL
);

ALTER TABLE vyucujici ADD CONSTRAINT vyucujici_pk PRIMARY KEY ( id_vyucujiciho );

CREATE TABLE zpusob_vyuky (
    id_zv    NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    zpusob   VARCHAR2(30) NOT NULL
);

ALTER TABLE zpusob_vyuky ADD CONSTRAINT zpusob_vyuky_pk PRIMARY KEY ( id_zv );

CREATE TABLE zpusob_zakonceni (
    id_zz        NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    zpusob_zak   VARCHAR2(20) NOT NULL
);

ALTER TABLE zpusob_zakonceni ADD CONSTRAINT zpusob_zakonceni_pk PRIMARY KEY ( id_zz );

ALTER TABLE katedra
    ADD CONSTRAINT katedra_fakulta_fk FOREIGN KEY ( fakulta_zkratka_fakulty )
        REFERENCES fakulta ( zkratka_fakulty );

ALTER TABLE obor
    ADD CONSTRAINT obor_fakulta_fk FOREIGN KEY ( fakulta_zkratka_fakulty )
        REFERENCES fakulta ( zkratka_fakulty );

ALTER TABLE obor_predmet
    ADD CONSTRAINT obor_predmet_kat_pred_fk FOREIGN KEY ( kategorie_predmetu_kategorie )
        REFERENCES kategorie_predmetu ( kategorie );

ALTER TABLE obor_predmet
    ADD CONSTRAINT obor_predmet_obor_fk FOREIGN KEY ( obor_zkratka_oboru )
        REFERENCES obor ( zkratka_oboru );

ALTER TABLE obor_predmet
    ADD CONSTRAINT obor_predmet_predmet_fk FOREIGN KEY ( predmet_zkratka_predmetu )
        REFERENCES predmet ( zkratka_predmetu );

ALTER TABLE predmet
    ADD CONSTRAINT predmet_forma_vyuky_fk FOREIGN KEY ( forma_vyuky_id_fv )
        REFERENCES forma_vyuky ( id_fv );

ALTER TABLE predmet
    ADD CONSTRAINT predmet_semestr_fk FOREIGN KEY ( semestr_id_semestr )
        REFERENCES semestr ( id_semestr );

ALTER TABLE predmet
    ADD CONSTRAINT predmet_zpusob_zakonceni_fk FOREIGN KEY ( zpusob_zakonceni_id_zz )
        REFERENCES zpusob_zakonceni ( id_zz );

ALTER TABLE rozvrhova_akce
    ADD CONSTRAINT rozvrhova_akce_predmet_fk FOREIGN KEY ( predmet_zkratka_predmetu )
        REFERENCES predmet ( zkratka_predmetu );

ALTER TABLE rozvrhova_akce
    ADD CONSTRAINT rozvrh_akce_role_vyuc_fk FOREIGN KEY ( role_vyucujiciho_role )
        REFERENCES role_vyucujiciho ( role );

ALTER TABLE rozvrhova_akce
    ADD CONSTRAINT rozvrhova_akce_vyucujici_fk FOREIGN KEY ( vyucujici_id_vyucujiciho )
        REFERENCES vyucujici ( id_vyucujiciho );

ALTER TABLE rozvrhova_akce
    ADD CONSTRAINT rozvrhova_akce_zpusob_vyuky_fk FOREIGN KEY ( zpusob_vyuky_id_zv )
        REFERENCES zpusob_vyuky ( id_zv );

ALTER TABLE vyucujici
    ADD CONSTRAINT vyucujici_katedra_fk FOREIGN KEY ( katedra_zkratka_katedry )
        REFERENCES katedra ( zkratka_katedry );*/

select * from VYUCUJICI 
    left join KATEDRA on VYUCUJICI.KATEDRA_ZKRATKA_KATEDRY = KATEDRA.ZKRATKA_KATEDRY
    left join FAKULTA on KATEDRA.FAKULTA_ZKRATKA_FAKULTY = FAKULTA.ZKRATKA_FAKULTY;
    
select * from rozvrhova_akce
    inner join VYUCUJICI on ROZVRHOVA_AKCE.VYUCUJICI_ID_VYUCUJICIHO = VYUCUJICI.ID_VYUCUJICIHO
    left join KATEDRA on VYUCUJICI.KATEDRA_ZKRATKA_KATEDRY = KATEDRA.ZKRATKA_KATEDRY
    left join FAKULTA on KATEDRA.FAKULTA_ZKRATKA_FAKULTY = FAKULTA.ZKRATKA_FAKULTY
    inner join PREDMET on ROZVRHOVA_AKCE.PREDMET_ZKRATKA_PREDMETU = PREDMET.ZKRATKA_PREDMETU;
    
select * from KATEDRA
    left join FAKULTA on KATEDRA.FAKULTA_ZKRATKA_FAKULTY = FAKULTA.ZKRATKA_FAKULTY;
    
create or replace view PRACOVISTE as 
    select * from KATEDRA
        left join FAKULTA on FAKULTA.ZKRATKA_FAKULTY = KATEDRA.FAKULTA_ZKRATKA_FAKULTY;
        
create or replace view PREDMET_EXT_VIEW as        
    select ZKRATKA_PREDMETU, NAZEV_PREDMETU, DOPORUCENY_ROCNIK, SEMESTR_ID_SEMESTR, ZPUSOB_ZAKONCENI_ID_ZZ, FORMA_VYUKY_ID_FV, SEM, ZPUSOB_ZAK, FORMA, SUM(POCET_STUDENTU) as POCET_STUDENTU from PREDMET
        left join SEMESTR on PREDMET.SEMESTR_ID_SEMESTR = SEMESTR.ID_SEMESTR 
        left join ZPUSOB_ZAKONCENI ON PREDMET.ZPUSOB_ZAKONCENI_ID_ZZ = ZPUSOB_ZAKONCENI.ID_ZZ
        left join FORMA_VYUKY on PREDMET.FORMA_VYUKY_ID_FV = FORMA_VYUKY.ID_FV
        left join ROZVRHOVA_AKCE on PREDMET.ZKRATKA_PREDMETU = ROZVRHOVA_AKCE.PREDMET_ZKRATKA_PREDMETU group by ZKRATKA_PREDMETU, NAZEV_PREDMETU, DOPORUCENY_ROCNIK, SEMESTR_ID_SEMESTR, ZPUSOB_ZAKONCENI_ID_ZZ, 
FORMA_VYUKY_ID_FV, SEM, ZPUSOB_ZAK, FORMA;

create or replace view SPOJENI_OBORU_PREDMETU_VIEW as        
    select ZKRATKA_OBORU, NAZEV_OBORU, ZKRATKA_PREDMETU, NAZEV_PREDMETU, KATEGORIE_PREDMETU_KATEGORIE, DOPORUCENY_ROCNIK, SEM, ZPUSOB_ZAK, FORMA from OBOR_PREDMET
        inner join PREDMET on OBOR_PREDMET.PREDMET_ZKRATKA_PREDMETU = PREDMET.ZKRATKA_PREDMETU
        inner join OBOR on OBOR_PREDMET.OBOR_ZKRATKA_OBORU = OBOR.ZKRATKA_OBORU
        left join SEMESTR on PREDMET.SEMESTR_ID_SEMESTR = SEMESTR.ID_SEMESTR 
        left join ZPUSOB_ZAKONCENI ON PREDMET.ZPUSOB_ZAKONCENI_ID_ZZ = ZPUSOB_ZAKONCENI.ID_ZZ
        left join FORMA_VYUKY on PREDMET.FORMA_VYUKY_ID_FV = FORMA_VYUKY.ID_FV;
        
create or replace view ROZVRHOVE_AKCE_EXT_VIEW as
    select ID_RA as ID_ROZVRHOVE_AKCE, POCET_STUDENTU, MAHODIN, ZACINAV, ROLE_VYUCUJICIHO_ROLE, PREDMET_ZKRATKA_PREDMETU as ZKRATKA_PREDMETU, VYUCUJICI_ID_VYUCUJICIHO as ID_VYUCUJICIHO, NAZEV_PREDMETU, DOPORUCENY_ROCNIK, ZPUSOB, JMENO as JMENO_VYUCUJICIHO, PRIJMENI as PRIJMENI_VYUCUJICIHO, TITUL_PRED, TITUL_ZA, TELEFON, MOBIL, EMAIL, KATEDRA_ZKRATKA_KATEDRY from ROZVRHOVA_AKCE
        inner join PREDMET on ROZVRHOVA_AKCE.PREDMET_ZKRATKA_PREDMETU = PREDMET.ZKRATKA_PREDMETU
        left join ZPUSOB_VYUKY on ROZVRHOVA_AKCE.ZPUSOB_VYUKY_ID_ZV = ZPUSOB_VYUKY.ID_ZV
        left join VYUCUJICI on ROZVRHOVA_AKCE.VYUCUJICI_ID_VYUCUJICIHO = VYUCUJICI.ID_VYUCUJICIHO;
        
        
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1974','Eduard','Babulak','','','KIT','','','');
--Row 3
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('576','Michael','Baûant','Ing.','Ph.D.','KST','michael.bazant@upce.cz','466 037 224','');
--Row 4
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('577','Miroslav','BenedikoviË','RNDr.','','KST','bene@fria.fri.utc.sk','','');
--Row 5
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6828','Ladislav','Beran','Ing.','','KE','st25775@student.upce.cz','','');
--Row 6
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('608','Pavel','Bezouöek','prof. Ing.','CSc.','KE','pavel.bezousek@upce.cz','','');
--Row 7
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4597','VojtÏch','Biberle','Ing.','','KIT','vojtech.biberle@upce.cz','','');
--Row 8
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5667','Ji¯Ì','Blecha','Ing.','','KE','','','');
--Row 9
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4168','Ag·ta','Bodn·rov·','Ing.','','KE','agata.bodnarova@gmail.com','','');
--Row 10
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6579','Ji¯Ì','Boch','','','KE','','','');
--Row 11
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5117','Monika','Borkovcov·','Ing.','Ph.D.','KIT','monika.borkovcova@upce.cz','','');
--Row 12
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4159','Filip','Borovec','Bc.','','KST','','','');
--Row 13
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8472','Tereza','Bos·kov·','Mgr.','','FEI','tereza.bosakova@upce.cz','','');
--Row 14
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2211','Tom·ö','Brandejsk˝','doc. Ing.','Dr.','KST','Tomas.Brandejsky@upce.cz','','');
--Row 15
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5663','VladimÌr','Br·zda','Ing.','','KE','','','');
--Row 16
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2468','Pavel','Brom','Ing.','','KST','pavel.brom@upce.cz','','');
--Row 17
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6125','Josef','Broûek','Ing.','','KIT','josef.brozek@student.upce.cz','','');
--Row 18
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7186','Bohumil','BrtnÌk','Ing.','Dr.','KE','','','');
--Row 19
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6145','David','Bud·Ë','','','KIT','david.budac@upce.cz','','');
--Row 20
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3999','Luk·ö','CÌr','Ing.','','KIT','','','');
--Row 21
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2350','Jan','Cvejn','doc. Ing.','Ph.D.','KRP','jan.cvejn@upce.cz','','');
--Row 22
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7166','Ji¯Ì','»adek','Ing.','','FEI','jiri.cadek@student.upce.cz','','');
--Row 23
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1996','Luk·ö','»egan','Ing.','Ph.D.','KIT','lukas.cegan@upce.cz','','');
--Row 24
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4563','MatÏj','»ern˝','Ing.','','KE','matej.cerny@student.upce.cz','','');
--Row 25
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6580','Roman','Diviö','Ing.','','KST','roman.divis@student.upce.cz','','');
--Row 26
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6116','Monika','Dobeöov·','Ing.','','KIT','monika.dobesova@upce.cz','','');
--Row 27
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('625','Martin','Dobrovoln˝','Ing.','Ph.D.','KE','martin.dobrovolny@upce.cz','','');
--Row 28
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4162','Petr','Doleûel','doc. Ing.','Ph.D.','KRP','Petr.Dolezel@upce.cz','','');
--Row 29
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('425','Frantiöek','Duöek','doc. Ing.','CSc.','KRP','frantisek.dusek@upce.cz','','');
--Row 30
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5103','Michal','Dvo¯·k','Ing.','','FEI','michal.dvorak@student.upce.cz','','');
--Row 31
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8512','Miroslav','Dvo¯·k','Ing.','Dipl.tech.','KIT','miroslav.dvorak@upce.cz','','');
--Row 32
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2210','Tom·ö','Dvo¯·k','Ing.','','KST','','','');
--Row 33
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8141','Kamila','FaËevicov·','Mgr.','Ph.D.','KMF','','','');
--Row 34
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6117','Ilona','Fialov·','Ing.','','KIT','','','');
--Row 35
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1851','Tom·ö','Fidler','Ing.','','KST','tomas.fidler@tiscali.cz','466 036 475','');
--Row 36
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1927','Jan','Fikejz','Ing.','Ph.D.','KST','jan.fikejz@upce.cz','','');
--Row 37
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1875','Aleö','Filip','doc. Ing.','CSc.','KE','ales.filip@upce.cz','','');
--Row 38
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8149','Petr','Filip','Ing.','','KIT','petr.filip1@student.upce.cz','','');
--Row 39
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('611','Ond¯ej','Fiöer','doc. Ing.','CSc.','KE','ondrej.fiser@upce.cz','','');
--Row 40
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('485','Miroslav','Fribert','Ing.','Dr.','KE','miroslav.fribert@upce.cz','','');
--Row 41
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7741','LumÌr','Gago','Ing.','','KIT','lumir.gago@student.upce.cz','','');
--Row 42
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('627','Martin','H·jek','Ing.','','KE','martin.hajek@student.upce.cz','','');
--Row 43
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8143','David','HandlÌ¯','Ing.','','KIT','david.handlir@student.upce.cz','','');
--Row 44
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4566','Milan','Hanus','Ing.','','KE','Milan.Hanus@upce.cz','','');
--Row 45
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('426','Libor','HavlÌËek','Ing.','Ph.D.','KRP','libor.havlicek@upce.cz','','');
--Row 46
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8158','Martin','Haûer','Ing.','','KST','','','');
--Row 47
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7816','Jaroslav','Hlinka','Ing. Mgr.','Ph.D.','KRP','hlinka@cs.cas.cz','','');
--Row 48
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8271','Tom·ö','HniliËka','Ing.','','KE','tomas.hnilicka@student.upce.cz','','');
--Row 49
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7165','Filip','HolÌk','Ing.','','KIT','filip.holik@student.upce.cz','','');
--Row 50
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('427','Daniel','Honc','Ing.','Ph.D.','KRP','daniel.honc@upce.cz','','');
--Insert failed for rows  51  through  100 
--ORA-01400: do ("C##ST47130"."VYUCUJICI"."EMAIL") nelze vloûit hodnotu NULL
--Row 61
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5714','Michal','J·chim','Ing.','','KE','','','');
--Row 62
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7167','Martin','Jakeö','Ing.','','KST','martin.jakes@student.upce.cz','','');
--Row 63
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('614','Otakar','Jaroö','Ing.','','KE','','','');
--Row 64
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1317','Milan','Jav˘rek','doc. Ing.','CSc.','KRP','milan.javurek@upce.cz','','');
--Row 65
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1569','Radim','JelÌnek','Ing. Mgr.','Ph.D.','KIT','radim.jelinek@mmp.cz','','');
--Row 66
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8138','äimon','JelÌnek','Bc.','','KIT','','','');
--Row 67
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4604','Hana','JelÌnkov·','Mgr.','DiS.','KIT','hana.jelinkova@upce.cz','','');
--Row 68
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7464','Jakub','Je¯·bek','Ing.','','KE','','','');
--Row 69
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5659','Pavel','Jetensk˝','Ing.','Ph.D.','KIT','st33370@student.upce.cz','','');
--Row 70
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7870','Milan','JiËÌnsk˝','Ing.','','KRP','milan.jicinsky@student.upce.cz','','');
--Row 71
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4885','Petra','Ji¯iötov·','','','FEI','petra.jiristova@upce.cz','466 036 423','');
--Row 72
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5422','Marek','Jon·ö','Ing.','','KE','marek.jonas@student.upce.cz','','');
--Row 73
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8140','Karel','Juryca','Ing.','','KMF','karel.juryca@student.upce.cz','','');
--Row 74
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('275','Simeon','Karamazov','prof. Ing.','Dr.','KIT','simeon.karamazov@upce.cz','','');
--Row 75
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5743','Ond¯ej','Karas','Ing.','','KE','st12656@student.upce.cz','','');
--Row 76
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6592','ätÏp·n','Kart·k','Ing.','','KST','stepan.kartak@student.upce.cz','','');
--Row 77
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('553','AntonÌn','KaviËka','prof. Ing.','Ph.D.','KST','antonin.kavicka@upce.cz','466 036 645','');
--Row 78
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5095','Jan','Keller','Ing.','','KIT','jan.keller@student.upce.cz','','');
--Row 79
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3346','Zuzana','KleprlÌkov·','Ing.','','KIT','zuzana.kleprlikova@upce.cz','','');
--Row 80
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('615','Ji¯Ì','KoneËn˝','Ing.','Ph.D.','KE','jiri.konecny@upce.cz','','');
--Row 81
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3986','Luboö','Kopeck˝','Bc.','','KIT','','','');
--Row 82
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3259','ZbynÏk','Kopeck˝','Ing.','','KIT','zbynek.kopecky@upce.cz','','');
--Row 83
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5075','David','Kordek','Mgr.','','FEI','','','');
--Row 84
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4002','Pavla','Koù·tkov· Str·nsk·','Ing.','Ph.D.','KMF','pavla.kotatkovastranska@upce.cz','','');
--Row 85
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('430','Josef','Kotyk','doc. Ing.','CSc.','KRP','josef.kotyk@upce.cz','','');
--Row 86
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4592','Jaroslava','Kr·lov·','Ing.','','KRP','jaroslava.kralova@student.upce.cz','','');
--Row 87
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7735','Ji¯Ì','KratochvÌl','Ing.','','KIT','jiri.kratochvil@student.upce.cz','','');
--Row 88
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5096','David','KrejËa','Bc.','','KIT','','','');
--Row 89
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('431','Stanislav','KrejËÌ','doc. Ing.','CSc.','KRP','stanislav.krejci@upce.cz','','');
--Row 90
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8275','Tom·ö','KrejËÌ','Ing.','','KE','tomas.krejci2@student.upce.cz','','');
--Row 91
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3341','Jaroslav','K¯iËka','Ing.','Ph.D.','KE','jaroslav.kricka@upce.cz','','');
--Row 92
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5173','Pavel','K¯Ìû','Ing.','','KST','','','');
--Row 93
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6405','Ilona','KuËerov·','Bc.','','FEI','','','');
--Row 94
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6902','Nataliia','Kudriavtseva','Ing.','','KE','st44226@student.upce.cz','','');
--Row 95
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5666','VladimÌr','Kudyn','Ing.','Ph.D.','KE','kudyn@szdc.cz','','');
--Row 96
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4163','Libor','Kupka','Ing.','Ph.D.','KRP','Libor.Kupka@upce.cz','','');
--Row 97
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3844','V·clav','KviËera','Ing.','CSc.','KE','','','');
--Row 98
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5655','Ji¯Ì','Kysela','Ing.','Ph.D.','KIT','jiri.kysela@upce.cz','','');
--Row 99
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1992','Jaroslav','Lach','Ing.','','KST','jaroslav.lach@upce.cz','','');
--Row 100
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5665','Martin','Lauterbach','Ing.','','KE','st19560@student.upce.cz','','');
--Insert failed for rows  101  through  150 
--ORA-01400: do ("C##ST47130"."VYUCUJICI"."EMAIL") nelze vloûit hodnotu NULL
--Row 102
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6608','Michal','Lek˝r','Ing.','Ph.D.','KE','','','');
--Row 103
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('432','Ji¯Ì','Mach·Ëek','doc. Ing.','CSc.','KRP','jiri.machacek@upce.cz','','');
--Row 104
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2458','Miloslav','Mach·Ëek','Ing.','Ph.D.','KIT','miloslav.machacek@upce.cz','','');
--Row 105
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8579','Filip','MajerÌk','Ing.','','KST','st40429@student.upce.cz','','');
--Row 106
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5243','Jitka','M·lkov·','','','KRP','Jitka.Malkova@upce.cz','','');
--Row 107
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5421','Michal','MandlÌk','Ing.','Ph.D.','KE','michal.mandlik@student.upce.cz','','');
--Row 108
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5073','Jaroslav','Marek','Mgr.','Ph.D.','KMF','jaroslav.marek@upce.cz','','');
--Row 109
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2446','Josef','Marek','Ing.','CSc.','KE','josef.marek@upce.cz','','');
--Row 110
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3395','Jan','Mareö','Ing.','','KRP','','','');
--Row 111
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6486','Jan','Mareö','Ing.','Ph.D.','KST','Jan.Mares@vscht.cz','','');
--Row 112
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6135','Martin','Mariöka','Ing.','','KRP','mariska.martin@gmail.com','','');
--Row 113
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6640','Ond¯ej','Ma¯Ìk','Ing.','','KST','st22222@student.upce.cz','','');
--Row 114
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6115','David','Matouöek','Ing. Bc.','','KE','david.matousek@upce.cz','','');
--Row 115
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6238','Jakub','Mejznar','Ing.','','FEI','','','');
--Row 116
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6126','Lucie','Melicharov·','Mgr.','','KIT','Lucie.Vycitalova@upce.cz','','');
--Row 117
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7746','Jan','Merta','Ing.','','KST','jan.merta@student.upce.cz','','');
--Row 118
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4097','Jana','Mikuleck·','','','KRP','jana.mikulecka@upce.cz','','');
--Row 119
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6063','Olga','Mitchell','PhDr.','','FEI','olga.mitchell@upce.cz','+420466037268','');
--Row 120
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8511','Ivo','M¸ller','RNDr. et PhDr.','Ph.D.','KMF','ivo.muller@upce.cz','','');
--Row 121
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8262','Martin','Navr·til','Ing.','','KE','martin.navratil1@student.upce.cz','','');
--Row 122
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8513','Marie','NedvÏdov·','Ing.','','KMF','marie.nedvedova@student.upce.cz','','');
--Row 123
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('619','ZdenÏk','NÏmec','Ing.','Ph.D.','KE','zdenek.nemec@upce.cz','','');
--Row 124
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2616','SoÚa','Neradov·','Ing.','Ph.D.','KIT','sona.neradova@upce.cz','466 603 7004','');
--Row 125
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4161','Miroslav','NovosvÏtsk˝','Ing.','','KIT','miroslav.novosvetsky@student.upce.cz','','');
--Row 126
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7743','Darina','Novotn·','Mgr.','','KIT','darina.novotna@upce.cz','','');
--Row 127
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1098','Milan','Novotn˝','Mgr.','','KIT','milan.novotny@upce.cz','','');
--Row 128
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6620','Radek','Novotn˝','Ing.','','KST','','','');
--Row 129
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8075','Frantiöek','Ondr·Ëek','Ing.','Ph.D.','KE','','','');
--Row 130
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8510','Karel','Pastor','doc. Mgr.','Ph.D.','KMF','karel.pastor@upce.cz','','');
--Row 131
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8528','Martina','PavlaËkov·','RNDr.','Ph.D.','KMF','','','');
--Row 132
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7898','Viktor','Pek','Ing.','','KE','','','');
--Row 133
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4603','Ji¯Ì','Peöek','Ing.','','KE','st29660@student.upce.cz','','');
--Row 134
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5102','Petra','Peökov·','Ing.','','FEI','','','');
--Row 135
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6651','MatÏj','Petkov','Ing.','','KE','st18322@student.upce.cz','','');
--Row 136
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4601','Ond¯ej','Petrûilka','Bc.','','KIT','','','');
--Row 137
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1917','Jan','PidaniË','Ing.','Ph.D.','KE','jan.pidanic@upce.cz','','');
--Row 138
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6195','Milena','PodÏbradsk·','Ing.','','FEI','milena.cepcarova@upce.cz','','');
--Row 139
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4565','Marek','Pola','Ing.','Ph.D.','KE','marek.pola@upce.cz','','');
--Row 140
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7164','Alena','PozdÌlkov·','Mgr.','Ph.D.','KMF','alena.pozdilkova@upce.cz','','');
--Row 141
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5474','Jan','Pruöka','Ing.','','KRP','jan.pruska@projectsoft.cz','','');
--Row 142
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6118','Dana','P¯Ìvratsk·','Ing.','','KIT','dana.privratska@upce.cz','','');
--Row 143
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2565','ZdenÏk','P¯Ìvratsk˝','Ing.','','KIT','zdenek.privratsky@upce.cz','','');
--Row 144
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1251','Josef','Rak','RNDr.','Ph.D.','KMF','josef.rak@upce.cz','','');
--Row 145
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5664','Luboö','Rejfek','Ing.','','KE','st16660@student.upce.cz','','');
--Row 146
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6096','Ji¯Ì','RoleËek','Ing.','','KE','jiri.rolecek@upce.cz','','');
--Row 147
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2625','Pavel','RozsÌval','Ing.','','KE','pavel.rozsival@upce.cz','','');
--Row 148
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1231','Iva','RuliÊov·','RNDr.','','KMF','iva.rulicova@upce.cz','466 037 096','');
--Row 149
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6124','Emil','ÿezanina','Ing.','','KIT','emil.rezanina@upce.cz','','');
--Row 150
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8263','VojtÏch','Samot·n','Ing.','','KST','vojtech.samotan@student.upce.cz','','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6137','Tom·ö','Shejbal','Ing.','','KE','st22083@student.upce.cz','','');
--Row 153
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7984','Kl·ra','Schejbalov·','Bc.','','KE','klara.schejbalova@upce.cz','','');
--Row 154
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2689','S.','Scholle','Ing.','','KRP','','','');
--Row 155
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4508','VladimÌr','Sieber','Ing.','','KST','','','');
--Row 156
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('198','Stanislava','Sl·nsk·','Ing.','','KIT','stanislava.slanska@upce.cz','','');
--Row 157
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1100','Luk·ö','Sl·nsk˝','Ing.','','KIT','lukas.slansky@upce.cz','','');
--Row 158
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('266','Miroslav','Such˝','Mgr.','','KIT','','','');
--Row 159
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3392','Martin','Svoboda','RNDr.','','KMF','martin.svoboda@upce.cz','','');
--Row 160
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7744','Tom·ö','Svoboda','Ing.','','KIT','tomas.svoboda5@student.upce.cz','','');
--Row 161
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4584','Miroslav','äediv˝','Bc.','','KE','','','');
--Row 162
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3506','Pavel','äevËÌk','Mgr.','','KE','pavel.sevcik@purpure.cz','','');
--Row 163
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1993','ZdenÏk','äilar','Ing.','Ph.D.','KIT','zdenek.silar@upce.cz','','');
--Row 164
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('578','Karel','äimerda','Ing.','','KST','karel.simerda@upce.cz','','');
--Row 165
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2624','Pavel','äkrab·nek','Ing.','Ph.D.','KRP','pavel.skrabanek@upce.cz','','');
--Row 166
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('273','Karel','äotek','prof. Ing.','CSc.','KST','karel.sotek@upce.cz','466 036 508','');
--Row 167
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5092','Jan','ätafa','Ing.','','KIT','jan.stafa@student.upce.cz','','');
--Row 168
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6169','Stanislav','äùastn˝','Ing.','','KIT','stanislav.stastny@upce.cz','','');
--Row 169
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2444','Ladislav','ätÏp·nek','Ing.','','KE','','','');
--Row 170
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1097','Jaroslav','ätroch','Ing.','','KIT','j.stroch@seznam.cz','','');
--Row 171
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6136','Petr','äuba','Ing.','','KST','petr.suba@upce.cz','','');
--Row 172
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4562','Pavel','äubrt','Ing.','','KIT','','','');
--Row 173
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8154','Tom·ö','Tal·öek','Mgr.','','KMF','tomas.talasek@upce.cz','','');
--Row 174
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('433','Ivan','Taufer','prof. Ing.','DrSc.','KRP','ivan.taufer@upce.cz','','');
--Row 175
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4094','Lenka','Tobiökov·','Bc.','','FEI','lenka.tobiskova@upce.cz','','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8173','Ji¯Ì','TvrdÌk','Ing.','','KRP','jiri.tvrdik@student.upce.cz','','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5074','ZbynÏk','Urban','Mgr.','Ph.D.','KMF','zbynek.urban@upce.cz','','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5646','Tom·ö','V·Úa','Ing.','','KIT','st19054@student.upce.cz','','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('568','Petr','Vesel˝','Ing.','','KST','petr.vesely@upce.cz','466 036 531','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('3327','SoÚa','Vinopalov·','Mgr.','','KIT','','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('2443','Radim','Vondra','Ing.','Ph.D.','KE','','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6621','Jan','Vor·Ëek','','','KIT','jan.voracek@student.upce.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('7657','Jan','Vor·Ëek','Ing.','','KIT','jan.voracek@student.upce.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('183','Jaroslav','Voz·b','Mgr.','','KMF','jaroslav.vozab@upce.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5042','Janet','Wolf','Mgr.','','FEI','janet.wolf@upce.cz','+420466037268','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6138','Tom·ö','Z·labsk˝','Ing.','','KE','tomas.zalabsky@student.upce.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6239','LudÏk','ZaplatÌlek','Ing.','','KE','ludek.zaplatilek@student.upce.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('8666','Milan','Zapletal','Ing.','','KRP','milan.zapletal1@student.upce.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4164','Vadim','Z·vodn˝','Ing.','','KE','zavodnv@post.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('5647','Ji¯Ì','Zechmeister','Ing.','','KIT','Jiri.Zechmeister@upce.cz','','');

INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('4598','Jan','Zikl','Bc.','','KIT','st12581@student.upce.cz','','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('6254','Stanislav','Zitta','Ing.','','KST','stanislav.zitta@student.upce.cz','','');
INSERT INTO VYUCUJICI (ID_VYUCUJICIHO, JMENO, PRIJMENI, TITUL_PRED, TITUL_ZA, KATEDRA_ZKRATKA_KATEDRY, EMAIL, TELEFON, MOBIL) VALUES ('1870','David','é·k','RNDr.','Ph.D.','KIT','david.zak@upce.cz','','');
       
       
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('ISWE','Spr·va webserveru',1.0);
--Row 178
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IUDP','Architektura poËÌtaË˘',2.0);
--Row 179
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IVPH','V˝voj poËÌtaËov˝ch her',2.0);
--Row 180
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IWWW','N·vrh a tvorba WWW str·nek',2.0);
--Row 181
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IWWWE','N·vrh a tvorba WWW str·nek',2.0);
--Row 182
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IZALG','Z·klady algoritmizace',2.0);
--Row 183
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IZBPR','Zpracov·nÌ bakal·¯skÈ pr·ce',3.0);
--Row 184
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IZEK','Z·klady ekonomie',2.0);
--Row 185
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IZEKO','Z·klady ekonomie',2.0);
--Row 186
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IZKMA','Z·klady managementu',3.0);
--Row 187
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('IZMAR','Z·klady marketingu',3.0);
--Row 188
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('I3DGR','3D grafika',1.0);
--Row 189
INSERT INTO PREDMET (ZKRATKA_PREDMETU, NAZEV_PREDMETU, SEMESTR_ID_SEMESTR) VALUES ('PATSK','Architektury a techniky datab·zov˝ch sys',2.0);
--Row 190

